version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: api
       MYSQL_DATABASE: api
       MYSQL_USER: api
       MYSQL_PASSWORD: api

   api:
     depends_on:
       - db
     image: imedvediev/api-contract:0.0.1
     expose:
       - "8090-8100"
     ports:
       - "8080:8080"
       - "8090-8100:8090-8100"
     restart: always
     environment:
       API_DB_HOST: db:3306
       API_DB_PASSWORD: api
volumes:
    db_data: